/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashAnalyzeRouteImport } from './routes/_dash.analyze'
import { Route as DashOverviewRouteImport } from './routes/_dash.overview'
import { Route as DashReportsRouteImport } from './routes/_dash.reports'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as ReportCaseIdRouteImport } from './routes/report.$caseId'
import { Route as DashAppsIndexRouteImport } from './routes/_dash.apps.index'
import { Route as DashAppsIdRouteImport } from './routes/_dash.apps.$id'
import { Route as DashBrandsIndexRouteImport } from './routes/_dash.brands.index'
import { Route as DashBrandsBrandIdRouteImport } from './routes/_dash.brands.$brandId'
import { Route as DashCasesIndexRouteImport } from './routes/_dash.cases.index'
import { Route as DashCasesCaseIdRouteImport } from './routes/_dash.cases.$caseId'
import { Route as DashSocialIndexRouteImport } from './routes/_dash.social.index'
import { Route as DashSocialIdRouteImport } from './routes/_dash.social.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAnalyzeRoute = DashAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => DashRoute,
} as any)
const DashOverviewRoute = DashOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashRoute,
} as any)
const DashReportsRoute = DashReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const ReportCaseIdRoute = ReportCaseIdRouteImport.update({
  id: '/report/$caseId',
  path: '/report/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAppsIndexRoute = DashAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => DashRoute,
} as any)
const DashAppsIdRoute = DashAppsIdRouteImport.update({
  id: '/apps/$id',
  path: '/apps/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashBrandsIndexRoute = DashBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => DashRoute,
} as any)
const DashBrandsBrandIdRoute = DashBrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => DashRoute,
} as any)
const DashCasesIndexRoute = DashCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => DashRoute,
} as any)
const DashCasesCaseIdRoute = DashCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => DashRoute,
} as any)
const DashSocialIndexRoute = DashSocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => DashRoute,
} as any)
const DashSocialIdRoute = DashSocialIdRouteImport.update({
  id: '/social/$id',
  path: '/social/$id',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof DashAnalyzeRoute
  '/overview': typeof DashOverviewRoute
  '/reports': typeof DashReportsRoute
  '/settings': typeof DashSettingsRoute
  '/report/$caseId': typeof ReportCaseIdRoute
  '/apps/$id': typeof DashAppsIdRoute
  '/brands/$brandId': typeof DashBrandsBrandIdRoute
  '/cases/$caseId': typeof DashCasesCaseIdRoute
  '/social/$id': typeof DashSocialIdRoute
  '/apps/': typeof DashAppsIndexRoute
  '/brands/': typeof DashBrandsIndexRoute
  '/cases/': typeof DashCasesIndexRoute
  '/social/': typeof DashSocialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof DashAnalyzeRoute
  '/overview': typeof DashOverviewRoute
  '/reports': typeof DashReportsRoute
  '/settings': typeof DashSettingsRoute
  '/report/$caseId': typeof ReportCaseIdRoute
  '/apps/$id': typeof DashAppsIdRoute
  '/brands/$brandId': typeof DashBrandsBrandIdRoute
  '/cases/$caseId': typeof DashCasesCaseIdRoute
  '/social/$id': typeof DashSocialIdRoute
  '/apps': typeof DashAppsIndexRoute
  '/brands': typeof DashBrandsIndexRoute
  '/cases': typeof DashCasesIndexRoute
  '/social': typeof DashSocialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/_dash/analyze': typeof DashAnalyzeRoute
  '/_dash/overview': typeof DashOverviewRoute
  '/_dash/reports': typeof DashReportsRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/report/$caseId': typeof ReportCaseIdRoute
  '/_dash/apps/$id': typeof DashAppsIdRoute
  '/_dash/brands/$brandId': typeof DashBrandsBrandIdRoute
  '/_dash/cases/$caseId': typeof DashCasesCaseIdRoute
  '/_dash/social/$id': typeof DashSocialIdRoute
  '/_dash/apps/': typeof DashAppsIndexRoute
  '/_dash/brands/': typeof DashBrandsIndexRoute
  '/_dash/cases/': typeof DashCasesIndexRoute
  '/_dash/social/': typeof DashSocialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/report/$caseId'
    | '/apps/$id'
    | '/brands/$brandId'
    | '/cases/$caseId'
    | '/social/$id'
    | '/apps/'
    | '/brands/'
    | '/cases/'
    | '/social/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/report/$caseId'
    | '/apps/$id'
    | '/brands/$brandId'
    | '/cases/$caseId'
    | '/social/$id'
    | '/apps'
    | '/brands'
    | '/cases'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/_dash/analyze'
    | '/_dash/overview'
    | '/_dash/reports'
    | '/_dash/settings'
    | '/report/$caseId'
    | '/_dash/apps/$id'
    | '/_dash/brands/$brandId'
    | '/_dash/cases/$caseId'
    | '/_dash/social/$id'
    | '/_dash/apps/'
    | '/_dash/brands/'
    | '/_dash/cases/'
    | '/_dash/social/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  ReportCaseIdRoute: typeof ReportCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/analyze': {
      id: '/_dash/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof DashAnalyzeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/overview': {
      id: '/_dash/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashOverviewRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/reports': {
      id: '/_dash/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashReportsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/report/$caseId': {
      id: '/report/$caseId'
      path: '/report/$caseId'
      fullPath: '/report/$caseId'
      preLoaderRoute: typeof ReportCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/apps/': {
      id: '/_dash/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof DashAppsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/apps/$id': {
      id: '/_dash/apps/$id'
      path: '/apps/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof DashAppsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/brands/': {
      id: '/_dash/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof DashBrandsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/brands/$brandId': {
      id: '/_dash/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof DashBrandsBrandIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/cases/': {
      id: '/_dash/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof DashCasesIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/cases/$caseId': {
      id: '/_dash/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof DashCasesCaseIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/social/': {
      id: '/_dash/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof DashSocialIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/social/$id': {
      id: '/_dash/social/$id'
      path: '/social/$id'
      fullPath: '/social/$id'
      preLoaderRoute: typeof DashSocialIdRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAnalyzeRoute: typeof DashAnalyzeRoute
  DashOverviewRoute: typeof DashOverviewRoute
  DashReportsRoute: typeof DashReportsRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashAppsIdRoute: typeof DashAppsIdRoute
  DashBrandsBrandIdRoute: typeof DashBrandsBrandIdRoute
  DashCasesCaseIdRoute: typeof DashCasesCaseIdRoute
  DashSocialIdRoute: typeof DashSocialIdRoute
  DashAppsIndexRoute: typeof DashAppsIndexRoute
  DashBrandsIndexRoute: typeof DashBrandsIndexRoute
  DashCasesIndexRoute: typeof DashCasesIndexRoute
  DashSocialIndexRoute: typeof DashSocialIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAnalyzeRoute: DashAnalyzeRoute,
  DashOverviewRoute: DashOverviewRoute,
  DashReportsRoute: DashReportsRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashAppsIdRoute: DashAppsIdRoute,
  DashBrandsBrandIdRoute: DashBrandsBrandIdRoute,
  DashCasesCaseIdRoute: DashCasesCaseIdRoute,
  DashSocialIdRoute: DashSocialIdRoute,
  DashAppsIndexRoute: DashAppsIndexRoute,
  DashBrandsIndexRoute: DashBrandsIndexRoute,
  DashCasesIndexRoute: DashCasesIndexRoute,
  DashSocialIndexRoute: DashSocialIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  ReportCaseIdRoute: ReportCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
