import type {
  AppListing,
  AppState,
  Brand,
  Case,
  Evidence,
  Notification,
  SocialProfile,
  SuspiciousDomain,
  WarningSign,
} from "./types";

/** Fixed "now" for the sample so relative dates and charts are stable. */
export const SAMPLE_NOW = "2026-10-07T09:00:00Z";

const ev = (
  findingId: string,
  n: number,
  type: Evidence["type"],
  title: string,
  content: string,
  source: string,
  capturedAt: string,
): Evidence => ({ id: `${findingId}-e${n}`, findingId, type, title, content, source, capturedAt });

const w = (id: string, label: string, detail: string, evidenceIds: string[]): WarningSign => ({
  id,
  label,
  detail,
  evidenceIds,
});

export const SAMPLE_BRANDS: Brand[] = [
  {
    id: "lumora",
    name: "Lumora Pay",
    industry: "Fintech / Digital payments",
    initials: "LP",
    website: "https://lumorapay.example",
    approvedDomains: ["lumorapay.example", "help.lumorapay.example", "status.lumorapay.example"],
    socialHandles: [
      { platform: "X", handle: "lumorapay" },
      { platform: "Instagram", handle: "lumorapay" },
      { platform: "LinkedIn", handle: "lumora-pay" },
    ],
    officialApps: [
      { name: "Lumora Pay", packageId: "com.lumorapay.app", publisher: "Lumora Pay Ltd", store: "Google Play" },
    ],
    publishers: ["Lumora Pay Ltd"],
    partners: ["PayPoint Partners"],
    aliases: ["Lumora", "LumoraPay", "Lumora Wallet"],
    keywords: ["lumora", "lumora pay", "lumora support", "lumora wallet", "lumora verify"],
  },
  {
    id: "kestrel",
    name: "Kestrel Air",
    industry: "Aviation / Travel",
    initials: "KA",
    website: "https://kestrelair.example",
    approvedDomains: ["kestrelair.example", "book.kestrelair.example"],
    socialHandles: [
      { platform: "Instagram", handle: "kestrelair" },
      { platform: "X", handle: "kestrelair" },
    ],
    officialApps: [
      { name: "Kestrel Air", packageId: "com.kestrelair.mobile", publisher: "Kestrel Airways Group", store: "App Store" },
    ],
    publishers: ["Kestrel Airways Group"],
    partners: ["SkyTrip Travel Agency"],
    aliases: ["Kestrel", "Kestrel Airways", "KestrelMiles"],
    keywords: ["kestrel air", "kestrel refund", "kestrel miles", "kestrel flights"],
  },
];

export const SAMPLE_DOMAINS: SuspiciousDomain[] = [
  { id: "d-1", brandId: "lumora", domain: "lumora-support.example", firstSeen: "2026-09-21", note: "Not on Lumora Pay's approved-domain list. Referenced by a social profile, a giveaway account and an app listing." },
  { id: "d-2", brandId: "lumora", domain: "lumora-verify.example", firstSeen: "2026-09-02", note: "Not an approved domain. Referenced by a Telegram account and an app privacy policy." },
  { id: "d-3", brandId: "kestrel", domain: "kestrel-refunds.example", firstSeen: "2026-08-18", note: "Not an approved domain. Referenced by two social accounts and an app listing." },
];

const P = (p: Omit<SocialProfile, "kind">): SocialProfile => ({ kind: "profile", ...p });
const A = (a: Omit<AppListing, "kind">): AppListing => ({ kind: "app", ...a });

export const SAMPLE_PROFILES: SocialProfile[] = [
  P({
    id: "sp-1",
    brandId: "lumora",
    platform: "X",
    displayName: "Lumora Pay Support",
    username: "lumorapay_helpdesk",
    bio: "Official Lumora Pay Support 24/7 ✔ Account locked? DM us your registered email and the 6-digit code to restore access. Verify at lumora-support.example",
    url: "https://lumora-support.example/restore",
    followers: 1840,
    accountCreated: "2026-09-19",
    detectedAt: "2026-09-22T08:14:00Z",
    lastChecked: "2026-10-06T22:10:00Z",
    category: "Support impersonation",
    signals: { nameSimilarity: 0.9, logoSimilarity: 0.85, domainMismatch: true, supportClaim: true, suspiciousRequest: true, unrecognized: true },
    warnings: [
      w("w1", "Similar brand name", "Display name “Lumora Pay Support” closely matches the registered brand name.", ["sp-1-e1"]),
      w("w2", "Similar logo", "Profile image visually resembles the official Lumora Pay mark (sample similarity 0.85).", ["sp-1-e2"]),
      w("w3", "Unknown domain", "Links to lumora-support.example, which is not on the approved-domain list.", ["sp-1-e3"]),
      w("w4", "Suspicious support wording", "Bio claims to be “Official … Support” and asks users to DM one-time codes.", ["sp-1-e1", "sp-1-e4"]),
      w("w5", "Unrecognized account", "@lumorapay_helpdesk is not among Lumora Pay's registered handles.", ["sp-1-e5"]),
    ],
    evidence: [
      ev("sp-1", 1, "Excerpt", "Profile bio", "“Official Lumora Pay Support 24/7 ✔ Account locked? DM us your registered email and the 6-digit code to restore access.”", "X profile page (sample capture)", "2026-09-22T08:14:00Z"),
      ev("sp-1", 2, "Screenshot note", "Profile image comparison", "Avatar uses the same teal circle-and-arc shape as the official mark, with slightly different spacing.", "X profile page (sample capture)", "2026-09-22T08:14:00Z"),
      ev("sp-1", 3, "Domain record", "Linked URL", "https://lumora-support.example/restore — domain first observed 2026-09-21; not in approved list.", "Profile link field (sample capture)", "2026-09-22T08:15:00Z"),
      ev("sp-1", 4, "Excerpt", "Reply to customer", "“Please send the code you just received so our team can verify you.”", "Public reply thread (sample capture)", "2026-09-30T14:02:00Z"),
      ev("sp-1", 5, "Metadata", "Account metadata", "Account created 2026-09-19. Handle not listed in Brand Registry.", "Sample dataset", "2026-10-06T22:10:00Z"),
    ],
    missingInfo: ["Registrant details for lumora-support.example", "Whether any users were contacted by DM"],
    status: "Needs review",
    domainId: "d-1",
  }),
  P({
    id: "sp-2",
    brandId: "lumora",
    platform: "Instagram",
    displayName: "Lumora Rewards",
    username: "lumora.giveaways",
    bio: "🎉 Lumora Pay 5th Anniversary Giveaway! Claim $500 — connect your wallet at lumora-support.example/claim. Limited spots!",
    url: "https://lumora-support.example/claim",
    followers: 9210,
    accountCreated: "2026-09-24",
    detectedAt: "2026-09-26T11:40:00Z",
    lastChecked: "2026-10-06T21:55:00Z",
    category: "Giveaway / scam",
    signals: { nameSimilarity: 0.8, logoSimilarity: 0.8, domainMismatch: true, supportClaim: false, suspiciousRequest: true, unrecognized: true },
    warnings: [
      w("w1", "Similar brand name", "Uses “Lumora” with promotional wording.", ["sp-2-e1"]),
      w("w2", "Unknown domain", "Links to lumora-support.example — the same unapproved domain as @lumorapay_helpdesk.", ["sp-2-e2"]),
      w("w3", "Suspicious request", "Asks users to “connect your wallet” to claim a cash prize.", ["sp-2-e1"]),
      w("w4", "Unrecognized account", "Not a registered Lumora Pay handle.", ["sp-2-e3"]),
    ],
    evidence: [
      ev("sp-2", 1, "Excerpt", "Giveaway post", "“Claim $500 — connect your wallet at lumora-support.example/claim. Limited spots!”", "Instagram post (sample capture)", "2026-09-26T11:40:00Z"),
      ev("sp-2", 2, "Domain record", "Linked URL", "https://lumora-support.example/claim", "Bio link (sample capture)", "2026-09-26T11:41:00Z"),
      ev("sp-2", 3, "Metadata", "Account metadata", "Account created 2026-09-24.", "Sample dataset", "2026-10-06T21:55:00Z"),
    ],
    missingInfo: ["Whether Lumora Pay is running any anniversary promotion"],
    status: "Needs review",
    domainId: "d-1",
  }),
  P({
    id: "sp-3",
    brandId: "lumora",
    platform: "X",
    displayName: "Lumora Pay",
    username: "lumorapay",
    bio: "Pay, send and save with Lumora. Support: help.lumorapay.example — we will never ask for your codes.",
    url: "https://lumorapay.example",
    followers: 182000,
    accountCreated: "2020-03-11",
    detectedAt: "2026-07-20T09:00:00Z",
    lastChecked: "2026-10-06T22:00:00Z",
    category: "Official account",
    signals: { nameSimilarity: 1, logoSimilarity: 1, domainMismatch: false, supportClaim: false, suspiciousRequest: false, unrecognized: false },
    warnings: [],
    evidence: [ev("sp-3", 1, "Metadata", "Registry match", "Handle @lumorapay is listed in Brand Registry as official.", "Brand Registry", "2026-10-06T22:00:00Z")],
    missingInfo: [],
    status: "Official",
  }),
  P({
    id: "sp-4",
    brandId: "lumora",
    platform: "Facebook",
    displayName: "PayPoint Partners — Lumora Reseller",
    username: "paypoint_lumora",
    bio: "Authorized Lumora Pay reseller for merchant terminals. Official site: lumorapay.example/partners",
    url: "https://lumorapay.example/partners",
    followers: 3400,
    accountCreated: "2022-05-02",
    detectedAt: "2026-08-04T10:00:00Z",
    lastChecked: "2026-10-05T12:00:00Z",
    category: "Authorized reseller",
    signals: { nameSimilarity: 0.5, logoSimilarity: 0.6, domainMismatch: false, supportClaim: false, suspiciousRequest: false, unrecognized: false },
    warnings: [],
    evidence: [ev("sp-4", 1, "Metadata", "Partner match", "“PayPoint Partners” is listed as an authorized partner.", "Brand Registry", "2026-10-05T12:00:00Z")],
    missingInfo: [],
    status: "Authorized",
  }),
  P({
    id: "sp-5",
    brandId: "lumora",
    platform: "Reddit",
    displayName: "Lumora Fans (unofficial)",
    username: "lumorafans",
    bio: "Fan community for Lumora Pay users. Not affiliated with Lumora Pay Ltd.",
    url: "",
    followers: 1250,
    accountCreated: "2023-01-15",
    detectedAt: "2026-08-12T10:00:00Z",
    lastChecked: "2026-10-04T08:00:00Z",
    category: "Fan account",
    signals: { nameSimilarity: 0.7, logoSimilarity: 0.5, domainMismatch: false, supportClaim: false, suspiciousRequest: false, unrecognized: false },
    warnings: [],
    evidence: [ev("sp-5", 1, "Excerpt", "Disclaimer", "“Not affiliated with Lumora Pay Ltd.”", "Community description (sample capture)", "2026-10-04T08:00:00Z")],
    missingInfo: [],
    status: "Dismissed",
    statusReason: "Clearly labelled fan account",
  }),
  P({
    id: "sp-6",
    brandId: "lumora",
    platform: "Telegram",
    displayName: "Lumora Verify Team",
    username: "lumora_verify_team",
    bio: "Lumora account verification desk. Complete KYC in 2 minutes at lumora-verify.example to avoid suspension.",
    url: "https://lumora-verify.example",
    followers: 640,
    accountCreated: "2026-08-30",
    detectedAt: "2026-09-03T16:20:00Z",
    lastChecked: "2026-10-06T20:00:00Z",
    category: "Brand impersonation",
    signals: { nameSimilarity: 0.75, logoSimilarity: 0.6, domainMismatch: true, supportClaim: true, suspiciousRequest: true, unrecognized: true },
    warnings: [
      w("w1", "Verification claim", "Presents itself as a Lumora verification desk.", ["sp-6-e1"]),
      w("w2", "Unknown domain", "Links to lumora-verify.example, which is not approved.", ["sp-6-e2"]),
      w("w3", "Urgency / suspension threat", "Warns of suspension to prompt quick action.", ["sp-6-e1"]),
    ],
    evidence: [
      ev("sp-6", 1, "Excerpt", "Channel description", "“Complete KYC in 2 minutes … to avoid suspension.”", "Telegram channel (sample capture)", "2026-09-03T16:20:00Z"),
      ev("sp-6", 2, "Domain record", "Linked URL", "https://lumora-verify.example", "Channel link (sample capture)", "2026-09-03T16:21:00Z"),
    ],
    missingInfo: ["Channel admin identity"],
    status: "Marked for review",
    domainId: "d-2",
  }),
  P({
    id: "sp-7",
    brandId: "lumora",
    platform: "TikTok",
    displayName: "lumora deals",
    username: "lumoradeals",
    bio: "deals & cashback tips 💸",
    url: "",
    followers: 310,
    accountCreated: "2026-07-01",
    detectedAt: "2026-07-28T13:00:00Z",
    lastChecked: "2026-10-02T10:00:00Z",
    category: "Insufficient evidence",
    signals: { nameSimilarity: 0.7, logoSimilarity: 0.4, domainMismatch: false, supportClaim: false, suspiciousRequest: false, unrecognized: true },
    warnings: [w("w1", "Uses brand keyword", "Username contains “lumora” but no other indicators were observed.", ["sp-7-e1"])],
    evidence: [ev("sp-7", 1, "Excerpt", "Bio", "“deals & cashback tips 💸”", "TikTok profile (sample capture)", "2026-07-28T13:00:00Z")],
    missingInfo: ["Post content", "Linked website", "Any brand claims"],
    status: "Dismissed",
    statusReason: "Insufficient evidence",
  }),
  P({
    id: "sp-8",
    brandId: "kestrel",
    platform: "Instagram",
    displayName: "Kestrel Air",
    username: "kestrelair",
    bio: "Fly further with Kestrel ✈ Manage bookings at kestrelair.example",
    url: "https://kestrelair.example",
    followers: 96000,
    accountCreated: "2019-06-01",
    detectedAt: "2026-07-18T09:00:00Z",
    lastChecked: "2026-10-06T19:00:00Z",
    category: "Official account",
    signals: { nameSimilarity: 1, logoSimilarity: 1, domainMismatch: false, supportClaim: false, suspiciousRequest: false, unrecognized: false },
    warnings: [],
    evidence: [ev("sp-8", 1, "Metadata", "Registry match", "Handle @kestrelair is listed as official.", "Brand Registry", "2026-10-06T19:00:00Z")],
    missingInfo: [],
    status: "Official",
  }),
  P({
    id: "sp-9",
    brandId: "kestrel",
    platform: "X",
    displayName: "Kestrel Air Customer Care",
    username: "kestrel_care_desk",
    bio: "Flight cancelled? We process refunds within 24h. Submit your card details at kestrel-refunds.example",
    url: "https://kestrel-refunds.example",
    followers: 2210,
    accountCreated: "2026-08-15",
    detectedAt: "2026-08-19T07:30:00Z",
    lastChecked: "2026-10-06T18:00:00Z",
    category: "Support impersonation",
    signals: { nameSimilarity: 0.85, logoSimilarity: 0.7, domainMismatch: true, supportClaim: true, suspiciousRequest: false, unrecognized: true },
    warnings: [
      w("w1", "Similar brand name", "“Kestrel Air Customer Care” matches the brand name.", ["sp-9-e1"]),
      w("w2", "Unknown domain", "Links to kestrel-refunds.example.", ["sp-9-e2"]),
      w("w3", "Support claim", "Claims to process refunds on Kestrel's behalf.", ["sp-9-e1"]),
    ],
    evidence: [
      ev("sp-9", 1, "Excerpt", "Bio", "“We process refunds within 24h. Submit your card details …”", "X profile (sample capture)", "2026-08-19T07:30:00Z"),
      ev("sp-9", 2, "Domain record", "Linked URL", "https://kestrel-refunds.example", "Profile link (sample capture)", "2026-08-19T07:31:00Z"),
    ],
    missingInfo: ["Direct message content"],
    status: "Marked for review",
    domainId: "d-3",
  }),
  P({
    id: "sp-10",
    brandId: "kestrel",
    platform: "Facebook",
    displayName: "Kestrel Free Flights 2026",
    username: "kestrel.freeflights",
    bio: "Share this post & win 2 free return tickets! Register at kestrel-refunds.example/win",
    url: "https://kestrel-refunds.example/win",
    followers: 15400,
    accountCreated: "2026-09-01",
    detectedAt: "2026-09-05T12:10:00Z",
    lastChecked: "2026-10-06T17:00:00Z",
    category: "Giveaway / scam",
    signals: { nameSimilarity: 0.8, logoSimilarity: 0.9, domainMismatch: true, supportClaim: false, suspiciousRequest: true, unrecognized: true },
    warnings: [
      w("w1", "Similar logo", "Uses the official Kestrel bird mark.", ["sp-10-e1"]),
      w("w2", "Unknown domain", "Links to kestrel-refunds.example.", ["sp-10-e2"]),
      w("w3", "Prize request", "Requires registration on an unapproved site to claim a prize.", ["sp-10-e2"]),
    ],
    evidence: [
      ev("sp-10", 1, "Screenshot note", "Cover image", "Cover image reproduces the Kestrel bird mark and livery colours.", "Facebook page (sample capture)", "2026-09-05T12:10:00Z"),
      ev("sp-10", 2, "Excerpt", "Pinned post", "“Register at kestrel-refunds.example/win”", "Facebook post (sample capture)", "2026-09-05T12:11:00Z"),
    ],
    missingInfo: [],
    status: "Needs review",
    domainId: "d-3",
  }),
  P({
    id: "sp-11",
    brandId: "kestrel",
    platform: "Instagram",
    displayName: "Kestrel Spotters — fan page",
    username: "kestrelspotters",
    bio: "Aviation photography fan page. Not affiliated with Kestrel Air.",
    url: "",
    followers: 5200,
    accountCreated: "2021-04-10",
    detectedAt: "2026-08-01T10:00:00Z",
    lastChecked: "2026-10-01T10:00:00Z",
    category: "Fan account",
    signals: { nameSimilarity: 0.6, logoSimilarity: 0.3, domainMismatch: false, supportClaim: false, suspiciousRequest: false, unrecognized: false },
    warnings: [],
    evidence: [ev("sp-11", 1, "Excerpt", "Disclaimer", "“Not affiliated with Kestrel Air.”", "Instagram bio (sample capture)", "2026-10-01T10:00:00Z")],
    missingInfo: [],
    status: "Dismissed",
    statusReason: "Clearly labelled fan account",
  }),
  P({
    id: "sp-12",
    brandId: "kestrel",
    platform: "LinkedIn",
    displayName: "Kestrel Travel Hub",
    username: "kestreltravelhub",
    bio: "Travel news and tips.",
    url: "",
    followers: 120,
    accountCreated: "2026-06-20",
    detectedAt: "2026-09-29T09:00:00Z",
    lastChecked: "2026-10-03T09:00:00Z",
    category: "Insufficient evidence",
    signals: { nameSimilarity: 0.6, logoSimilarity: 0.2, domainMismatch: false, supportClaim: false, suspiciousRequest: false, unrecognized: true },
    warnings: [w("w1", "Uses brand keyword", "Name contains “Kestrel”; no other indicators.", ["sp-12-e1"])],
    evidence: [ev("sp-12", 1, "Excerpt", "Headline", "“Travel news and tips.”", "LinkedIn page (sample capture)", "2026-09-29T09:00:00Z")],
    missingInfo: ["Posts", "Website", "Brand claims"],
    status: "Needs review",
  }),
];

export const SAMPLE_APPS: AppListing[] = [
  A({
    id: "ap-1",
    brandId: "lumora",
    name: "Lumora Wallet Pro",
    store: "Google Play (sample listing)",
    publisher: "LMR Digital Tools",
    packageId: "com.lmrdigital.walletpro",
    description: "Official Lumora Pay wallet upgrade. Restore locked accounts instantly with our support team. Visit lumora-support.example.",
    website: "https://lumora-support.example",
    privacyDomain: "lumora-support.example",
    detectedAt: "2026-09-24T10:05:00Z",
    lastChecked: "2026-10-06T22:20:00Z",
    category: "Suspicious app",
    signals: { nameSimilarity: 0.85, iconSimilarity: 0.9, publisherMismatch: true, domainMismatch: true, suspiciousWording: true },
    warnings: [
      w("w1", "Similar icon", "Icon closely resembles the official Lumora Pay icon (sample similarity 0.90).", ["ap-1-e1"]),
      w("w2", "Publisher mismatch", "“LMR Digital Tools” is not a registered Lumora Pay publisher.", ["ap-1-e2"]),
      w("w3", "Shared unknown domain", "Developer website is lumora-support.example — also used by two social profiles.", ["ap-1-e3"]),
      w("w4", "Suspicious description", "Claims to be “Official” and offers account restoration.", ["ap-1-e4"]),
    ],
    evidence: [
      ev("ap-1", 1, "Screenshot note", "Icon comparison", "Teal circle-and-arc icon nearly identical to official app icon.", "Store listing (sample capture)", "2026-09-24T10:05:00Z"),
      ev("ap-1", 2, "Store listing", "Publisher field", "Publisher: LMR Digital Tools. Registered publishers: Lumora Pay Ltd.", "Store listing (sample capture)", "2026-09-24T10:05:00Z"),
      ev("ap-1", 3, "Domain record", "Developer website", "https://lumora-support.example", "Store listing (sample capture)", "2026-09-24T10:06:00Z"),
      ev("ap-1", 4, "Excerpt", "Description", "“Official Lumora Pay wallet upgrade. Restore locked accounts instantly …”", "Store listing (sample capture)", "2026-09-24T10:06:00Z"),
    ],
    missingInfo: ["Install count", "App binary analysis (out of scope)"],
    permissions: ["Read SMS", "Display over other apps"],
    status: "Needs review",
    domainId: "d-1",
  }),
  A({
    id: "ap-2",
    brandId: "lumora",
    name: "Lumora Pay",
    store: "Google Play (sample listing)",
    publisher: "Lumora Pay Ltd",
    packageId: "com.lumorapay.app",
    description: "Pay, send and save with Lumora.",
    website: "https://lumorapay.example",
    privacyDomain: "lumorapay.example",
    detectedAt: "2026-07-20T09:00:00Z",
    lastChecked: "2026-10-06T22:00:00Z",
    category: "Official app",
    signals: { nameSimilarity: 1, iconSimilarity: 1, publisherMismatch: false, domainMismatch: false, suspiciousWording: false },
    warnings: [],
    evidence: [ev("ap-2", 1, "Metadata", "Registry match", "Package ID matches Brand Registry.", "Brand Registry", "2026-10-06T22:00:00Z")],
    missingInfo: [],
    status: "Official",
  }),
  A({
    id: "ap-3",
    brandId: "lumora",
    name: "Lumora Verify Assistant",
    store: "Third-party APK site (sample)",
    publisher: "Verify Apps Co",
    packageId: "co.verifyapps.lumora",
    description: "Verify your Lumora account fast. Avoid suspension.",
    website: "https://verifyapps.example",
    privacyDomain: "lumora-verify.example",
    detectedAt: "2026-09-06T15:00:00Z",
    lastChecked: "2026-10-05T15:00:00Z",
    category: "Suspicious app",
    signals: { nameSimilarity: 0.7, iconSimilarity: 0.5, publisherMismatch: true, domainMismatch: true, suspiciousWording: true },
    warnings: [
      w("w1", "Unfamiliar publisher", "“Verify Apps Co” is not a registered publisher.", ["ap-3-e1"]),
      w("w2", "Privacy policy on unknown domain", "Privacy policy hosted on lumora-verify.example.", ["ap-3-e2"]),
    ],
    evidence: [
      ev("ap-3", 1, "Store listing", "Publisher", "Verify Apps Co", "APK site listing (sample capture)", "2026-09-06T15:00:00Z"),
      ev("ap-3", 2, "Domain record", "Privacy policy URL", "https://lumora-verify.example/privacy", "APK site listing (sample capture)", "2026-09-06T15:01:00Z"),
    ],
    missingInfo: ["Download count"],
    status: "Marked for review",
    domainId: "d-2",
  }),
  A({
    id: "ap-4",
    brandId: "kestrel",
    name: "Kestrel Air",
    store: "App Store (sample listing)",
    publisher: "Kestrel Airways Group",
    packageId: "com.kestrelair.mobile",
    description: "Book flights, check in and manage trips.",
    website: "https://kestrelair.example",
    privacyDomain: "kestrelair.example",
    detectedAt: "2026-07-18T09:00:00Z",
    lastChecked: "2026-10-06T19:00:00Z",
    category: "Official app",
    signals: { nameSimilarity: 1, iconSimilarity: 1, publisherMismatch: false, domainMismatch: false, suspiciousWording: false },
    warnings: [],
    evidence: [ev("ap-4", 1, "Metadata", "Registry match", "Package ID matches Brand Registry.", "Brand Registry", "2026-10-06T19:00:00Z")],
    missingInfo: [],
    status: "Official",
  }),
  A({
    id: "ap-5",
    brandId: "kestrel",
    name: "Kestrel Refund Tracker",
    store: "Google Play (sample listing)",
    publisher: "KR Travel Utils",
    packageId: "com.krtravel.refundtracker",
    description: "Track and claim your Kestrel Air refunds. Enter booking and card details to speed up payouts.",
    website: "https://kestrel-refunds.example",
    privacyDomain: "kestrel-refunds.example",
    detectedAt: "2026-08-22T09:00:00Z",
    lastChecked: "2026-10-06T16:00:00Z",
    category: "Suspicious app",
    signals: { nameSimilarity: 0.7, iconSimilarity: 0.6, publisherMismatch: true, domainMismatch: true, suspiciousWording: false },
    warnings: [
      w("w1", "Publisher mismatch", "“KR Travel Utils” is not a registered publisher.", ["ap-5-e1"]),
      w("w2", "Shared unknown domain", "Website kestrel-refunds.example is also linked by two social accounts.", ["ap-5-e2"]),
    ],
    evidence: [
      ev("ap-5", 1, "Store listing", "Publisher", "KR Travel Utils", "Store listing (sample capture)", "2026-08-22T09:00:00Z"),
      ev("ap-5", 2, "Domain record", "Developer website", "https://kestrel-refunds.example", "Store listing (sample capture)", "2026-08-22T09:01:00Z"),
    ],
    missingInfo: [],
    status: "Marked for review",
    domainId: "d-3",
  }),
  A({
    id: "ap-6",
    brandId: "kestrel",
    name: "Kestrel Miles Booster",
    store: "Google Play (sample listing)",
    publisher: "Unknown publisher",
    packageId: "app.milesbooster.kestrel",
    description: "Earn more miles.",
    website: "",
    privacyDomain: "",
    detectedAt: "2026-09-30T11:00:00Z",
    lastChecked: "2026-10-05T11:00:00Z",
    category: "Insufficient evidence",
    signals: { nameSimilarity: 0.6, iconSimilarity: 0.4, publisherMismatch: true, domainMismatch: false, suspiciousWording: false },
    warnings: [w("w1", "Unfamiliar publisher", "Publisher is not identified.", ["ap-6-e1"])],
    evidence: [ev("ap-6", 1, "Store listing", "Publisher", "Unknown publisher; no website or privacy policy listed.", "Store listing (sample capture)", "2026-09-30T11:00:00Z")],
    missingInfo: ["Developer website", "Privacy policy", "Publisher identity"],
    status: "Needs review",
  }),
];

const REVIEWER = "Priya Raman";

export const SAMPLE_CASES: Case[] = [
  {
    id: "CASE-1042",
    title: "Kestrel refund-domain cluster",
    brandId: "kestrel",
    priority: "High",
    assignee: REVIEWER,
    status: "Investigating",
    findingIds: ["sp-9", "sp-10", "ap-5"],
    summary: "Two social accounts and one app listing reference kestrel-refunds.example, an unapproved domain.",
    notes: "Waiting on Kestrel brand team to confirm no refund partner uses this domain.",
    activity: [
      { at: "2026-09-06T10:00:00Z", by: REVIEWER, text: "Case created" },
      { at: "2026-09-07T09:00:00Z", by: REVIEWER, text: "Status changed to Investigating" },
      { at: "2026-09-08T09:00:00Z", by: REVIEWER, text: "Added Kestrel Refund Tracker" },
    ],
    createdAt: "2026-09-06T10:00:00Z",
    updatedAt: "2026-09-08T09:00:00Z",
  },
  {
    id: "CASE-1041",
    title: "Lumora verification channel & app",
    brandId: "lumora",
    priority: "High",
    assignee: "Daniel Okafor",
    status: "Ready for review",
    findingIds: ["sp-6", "ap-3"],
    summary: "Telegram channel and APK listing both reference lumora-verify.example.",
    notes: "Evidence compiled. Ready for brand-team review.",
    activity: [
      { at: "2026-09-04T12:00:00Z", by: "Daniel Okafor", text: "Case created" },
      { at: "2026-09-10T12:00:00Z", by: "Daniel Okafor", text: "Status changed to Ready for review" },
    ],
    createdAt: "2026-09-04T12:00:00Z",
    updatedAt: "2026-09-10T12:00:00Z",
  },
  {
    id: "CASE-1039",
    title: "Kestrel Miles Booster listing",
    brandId: "kestrel",
    priority: "Medium",
    assignee: REVIEWER,
    status: "New",
    findingIds: ["ap-6"],
    summary: "Listing uses brand name with no identifiable publisher.",
    notes: "",
    activity: [{ at: "2026-10-01T08:00:00Z", by: REVIEWER, text: "Case created" }],
    createdAt: "2026-10-01T08:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
  },
  {
    id: "CASE-1035",
    title: "lumoradeals TikTok account",
    brandId: "lumora",
    priority: "Low",
    assignee: "Daniel Okafor",
    status: "Dismissed",
    findingIds: ["sp-7"],
    summary: "Account uses brand keyword only.",
    notes: "Dismissed — insufficient evidence. Re-check in 30 days.",
    activity: [
      { at: "2026-07-29T08:00:00Z", by: "Daniel Okafor", text: "Case created" },
      { at: "2026-08-02T08:00:00Z", by: "Daniel Okafor", text: "Status changed to Dismissed" },
    ],
    createdAt: "2026-07-29T08:00:00Z",
    updatedAt: "2026-08-02T08:00:00Z",
  },
];

export const SAMPLE_NOTIFICATIONS: Notification[] = [
  { id: "n1", title: "New critical finding", body: "@lumorapay_helpdesk on X scored 95/100 (sample heuristic).", at: "2026-10-06T22:10:00Z", read: false, link: "/social/sp-1" },
  { id: "n2", title: "Shared domain detected", body: "lumora-support.example is linked by 3 findings.", at: "2026-10-06T22:20:00Z", read: false, link: "/social/sp-1" },
  { id: "n3", title: "Case ready for review", body: "CASE-1041 moved to Ready for review.", at: "2026-09-10T12:00:00Z", read: true, link: "/cases/CASE-1041" },
];

export function createDefaultState(): AppState {
  return structuredClone({
    brands: SAMPLE_BRANDS,
    profiles: SAMPLE_PROFILES,
    apps: SAMPLE_APPS,
    domains: SAMPLE_DOMAINS,
    cases: SAMPLE_CASES,
    notifications: SAMPLE_NOTIFICATIONS,
    settings: {
      workspaceName: "NEXORA Workspace",
      defaultBrandId: "lumora",
      theme: "light",
      reviewerName: REVIEWER,
      reviewerRole: "Threat Analyst",
      notifyHighPriority: true,
      notifyCaseUpdates: true,
    },
    selectedBrandId: "lumora",
    dateRange: 90,
    customDateRange: null,
    lastScan: "2026-10-06T22:20:00Z",
  } satisfies AppState);
}
